#!/usr/bin/bash

p=~/.config/hypr/component/waybar/colors.css

if [[ $1 == *"city-blue"* ]]; then
    printf "@define-color c1 #1461c7;\n@define-color c2 #073470;" > $p
elif [[ $1 == *"city-purple"* ]]; then
    printf "@define-color c1 #302052;\n@define-color c2 #df9beb;" > $p
elif [[ $1 == *"day-green"* ]]; then
    printf "@define-color c1 #62a381;\n@define-color c2 #c7ffee;" > $p
elif [[ $1 == *"evening-pink"* ]]; then
    printf "@define-color c1 #e87de3;\n@define-color c2 #7f229c;" > $p
elif [[ $1 == *"morning-orange"* ]]; then
    printf "@define-color c1 #dba78a;\n@define-color c2 #bd4c20;" > $p
elif [[ $1 == *"morning-green"* ]]; then
    printf "@define-color c1 #337a78;\n@define-color c2 #81d6e3;" > $p
elif [[ $1 == *"night-blue"* ]]; then
    printf "@define-color c1 #3f3263;\n@define-color c2 #ac9cd6;" > $p
elif [[ $1 == *"red-blue"* ]]; then
    printf "@define-color c1 #6e222f;\n@define-color c2 #fa5b2a;" > $p
elif [[ $1 == *"space-blue"* ]]; then
    printf "@define-color c1 #00fbff;\n@define-color c2 #000000;" > $p
elif [[ $1 == *"winter-orange"* ]]; then
    printf "@define-color c1 #826c5e;\n@define-color c2 #c29b82;" > $p
fi

killall waybar expand
~/.config/hypr/scripts/launch_waybar