#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
#dunst &

# waybar
#$scripts/launch_waybar &
#$scripts/tools/dynamic &

# wallpaper
$scripts/wall ~/Pictures/wallpapers/fgvy78z6f0f61.jpg &

# effects
$scripts/rgb &

# other
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &