#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# wallpaper
$scripts/wall ~/Pictures/wallpapers/fgvy78z6f0f61.jpg &

# other
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Widgets
ags &